### ISSUE TITLE
Unable to Change Attachments Folder

### ISSUE THREAD

**Issue by jrebele** [joomlaworks/k2#118]
Folks,
I've noticed an issue with the "change root attachments folder".  I have change the value of this field in the Items area.  I click on Parameters and then the Advanced tab.  I've changed the folder to read "Content/".  I've moved all my files to this folder.  When I go to attempt to add an attachment using "browse on the server", the root folder is images/.  I cannot get this to change.  I am using Joomla! 3.2 with K2 2.6.7 and all my folders are writable.  Is this a bug or am I missing something here?

Thanks,
Joe

**Comment by kavadas** [comment]
The root folder that the media manager opens can be configured in the media manager and it has nothing to with the attachments folder.
