### ISSUE TITLE
Incorrect/unclear html attribute stripping behavior

### ISSUE THREAD

**Issue by creativeprogramming** [joomlaworks/k2#119]
Attribute filtering seems to ignore parent tag exclusions (maybe this is wanted but not clear).

How to reproduce:

* Create an item
* Put some links in the introtext, for instance: `<a href="https://github.com" target="_blank">github</a>`
* Save the item
* Go in Components -> K2 -> Params -> Content
* Set "Introtext HTML cleanup (tag strip)" to yes
* Set "Enter which HTML tags not to strip in fulltext" to "a,i,strong"
* Set "Enter which HTML tag attributes to strip in introtext" to "" (it means none right?)
* Go to the frontend previously created item url

You will get this on the item html:
```html
<a href target>github</a>
```
That is a broken link (and behave like a link to the article itself)

Now if "Enter which HTML tag attributes to strip in introtext" kept blank means clean all attributes this is not an issue but maybe a more clear label and more control on that (e.g another flag to disable attribute stripping) can improve this feature, because if i want only tag stripping but not attribute cleaning the only way now is to put some dummy attribute in "Enter which HTML tag attributes to strip in introtext" 

In addition there was an issue in the italian translation for "Enter which HTML tag attributes to strip in introtext" that was translated like "Enter which HTML tags to strip in fulltext", with no mention to attributes: i just submitted an improvement on transifex.

**Comment by kavadas** [comment]
Tested again with K2 2.7 development version and it works fine for me if you leave blank the option "Enter which HTML tag attributes to strip in introtext" .
