### ISSUE TITLE
BUG: Search-K2 plugin

### ISSUE THREAD

**Issue by rmuzzini** [joomlaworks/k2#126]
v. 2.6.8.
file k2.php
two bugs throw errors during search when "search in tags" is on.
line 91:
<code>$tagQuery = $db->Quote('%'.$escaped.'%', false);</code>
should be
<code>$quoted = $db->Quote('%'.$escaped.'%', false);</code>
line 121:
<code>$where .= " OR i.id IN (".implode(',', $itemIDs);</code>
should be
<code>$where .= " OR i.id IN (".implode(',', $itemIDs).")";</code>

**Comment by lutel** [comment]
This is really bad. Is it possible somehow to search by K2 tags either with Joomla/K2 or other plugins?

**Comment by impressionestudio** [comment]
I used K2 v.2.6.9 and sometimes in some searches the K2 search plugin showed an SQL error. I found the solution.

Go to the file "plugins/search/k2/k2.php" and change the line 122 from 
$where .= " OR i.id IN (".implode(',', $itemIDs);
to
$where .= " OR i.id IN (".implode(',', $itemIDs).")";

This worked for me.

**Comment by kavadas** [comment]
@impressionestudio 

As i wrote before this has been fixed already : https://github.com/joomlaworks/k2/blob/master/plugins/search/k2.php#L139 . 

In any case, thanks for reporting.
