### ISSUE TITLE
Default publishing state of new k2 items should be unpublished

### ISSUE THREAD

**Issue by SkGold** [joomlaworks/k2#18]
Default publishing state of new k2 items should be unpublished.

It doesn't make any sense to have it published as user who don't have permissions to publish items can create a new item and publish it at the same time.

Forum post [ http://getk2.org/community/New-to-K2-Ask-here-first/166475-new-article-default-state#182050 ]

**Comment by fevangelou** [comment]
Already implemented. Disallow the option for publishing for a specific user group.
