### ISSUE TITLE
Users import plugin issue

### ISSUE THREAD

**Issue by dazzlesoftware** [joomlaworks/k2#180]
Hello it seems the users import plugin effects the require reset password when enabled on Joomla that it goes on a loop and keeps re;turning to the page to reset the password.

after disabling the users import plugin on k2 everything works again using Joomla 3.3.1

is there any work around for this bug as it effects my whole system as I create users from game called second life and users need to make an password of there choice after I random generate them an password

Stephen

**Comment by kavadas** [comment]
This plugin is not part of K2. Closing the issue.
