### ISSUE TITLE
Missing Categories and Items in Backend.

### ISSUE THREAD

**Issue by K2Joom** [joomlaworks/k2#181]
What steps will reproduce the problem?
1. Setup default multilingual Joomla site, ie install en-gb, de, fr languages.
2. Create categories and items and set them to the required language.
3. K2 Category and Item list views will only display content that is set to ALL.  Any content set to any other language is not displayed.
4. Change the Category and/or Item language selector in list view in backend to one of the setup languages and the filter reverts back to showing just ALL language type content in the table.
5. If the ID of the category or Item is know, then the URL can be manually created in the address bar and the content shown.
6. Frontend display of content is not affected.

What is the expected output? What do you see instead?
Expected: See all items and categories for all language types.
See: Only content set to ALL language

What version of the product are you using? On what operating system?
K2 v2.6.8 (same issue on previous versions)
Joomla 2.5.22
Tested on Win XP, Win 7, Win Vista on Firefox, Chrome.
Browser and Site caches cleared.

All Joomla content and other extensions which have language support all work correctly.

**Comment by kavadas** [comment]
@K2Joom 

It's been a long time, are there any news on this? It's working fine for me under Joomla! 3.
