### ISSUE TITLE
forced use of mootool by calling JHTMLbehavior::modal on all items views

### ISSUE THREAD

**Issue by nonnenmacher** [joomlaworks/k2#21]
I'm trying to remove all links to mootools in a 2.5 version of a site.

Succeeded so far until I get into those lines in K2 Plug-in on the AfterRoute method 

if ( !$user->guest || (JRequest::getCmd('option') == 'com_k2' && JRequest::getCmd('view') == 'item') || defined('K2_JOOMLA_MODAL_REQUIRED') ){
			JHTML::_('behavior.modal');
		}

I don't understand why, you'd force use of this mootool modal, for example on people that use other modals (NoNumber modal come to mind).

Could there be a better way to use this K2 constant K2_JOOMLA_MODAL_REQUIRED ?

In front of this if statement an create a more meaningful logic shortcut along something like :+1: 
if ( defined('K2_JOOMLA_MODAL_REQUIRED') && ....

note : this kinda duplicate of tickets 68 and 582 on google issues.

**Comment by fevangelou** [comment]
The Joomla modal will be removed for non editing features in K2 2.7.0 thus resolving this issue.

**Comment by nonnenmacher** [comment]
would be perfect !!!!

Thanks in advance.
