### ISSUE TITLE
Use of extrafield header causes extrafields to always be shown

### ISSUE THREAD

**Issue by lemble** [joomlaworks/k2#218]
The use of one or more extrafields headers results in the extrafields section always being displayed in the front end even if no extrafields are held against an item as the header is counted as an extrafield (if the header is set to be published in the front end).

**Comment by kavadas** [comment]
A header is also an extra field, that's why it is displayed. I don't think there is a reason to change that. It will add complexity to the layout. You can always add your own code in a template override and apply your logic.
