### ISSUE TITLE
Select a K2 item in menu manager showing error 404 page not found in lightbox

### ISSUE THREAD

**Issue by amitgora27** [joomlaworks/k2#225]
![error](https://cloud.githubusercontent.com/assets/7251184/5777242/7c019d3c-9db6-11e4-84b5-254d3083a225.jpg)

I am not able to select a k2 item form list. It is showing error 404 page.

I have done all changes like put site url in configuration file, enable rewrite from global configuration.

Please provide me your email ID i will send my site details on that.

Regards,
Amit

**Comment by kavadas** [comment]
Which version of K2 are you using?

**Comment by amitgora27** [comment]
K2 v2.6.9 | Copyright © 2006-2015 JoomlaWorks Ltd. which is i am using.

**Comment by kricore** [comment]
This is really counterproductive.
Posting here and on the forum will not get the issue solved any faster.
This thread is for posting issues not receiving help. For receiving help please use the forum.

**Comment by kavadas** [comment]
As i can see you have already posted in our forum. This is a place for submitting issues not getting help. When the issue is confirmed and can be reproduced you can create a new issue here. Until then you need to keep using the forum. Finally, note that you have to respect the forum rules.
