### ISSUE TITLE
Allow to override template per menu item

### ISSUE THREAD

**Issue by smehrbrodt** [joomlaworks/k2#227]
I have a K2 category which is displayed in two different menu items. I want each menu item to have a different template.
However, I can only assign a template to a menu item when I select more than one category.

Can you add an option to assign a different template per menu item even if you select only one category?

**Comment by kavadas** [comment]
I don't think we are going to add this now. You can create an empty category and select it as the second category in the menu link.

**Comment by fevangelou** [comment]
To be added in K2 v2.7.0 and 3.0.0.
