### ISSUE TITLE
Joomla 3.4 - Multilanguage Error

### ISSUE THREAD

**Issue by mixino** [joomlaworks/k2#232]
Hello to all developers k2.

I found a problem with joomla 3.4 active multi language, when you create a new article (in administration) appears in a video allert "the item must have a title"

This bug does not occur "in my few tests" if installing joomla 3.4 is mono language.

I checked on my 3 sites and the bug is always creating a new article.

![schermata 2015-03-03 alle 18 02 59](https://cloud.githubusercontent.com/assets/5889220/6467709/3ac0429a-c1d0-11e4-83f3-f8c1fc337645.png)

Thanks best Regard

**Comment by kavadas** [comment]
Hi,

What's your K2 version? Are you using any K2/content plugins?

**Comment by mixino** [comment]
i tested k2 2.69 (and i test 2.7 dev)

Simple image Gallery PRO - All video

Thanks!

Read this

http://www.joomlaworks.net/forum/k2-en/40358-item-must-have-a-title-error-after-j3-4-upgrade

**Comment by mixino** [comment]
wow thanks :D @kavadas work perfect :)

**Comment by kavadas** [comment]
You are welcome.

**Comment by mixino** [comment]
@kavadas one my big question :)
can i ask you something about k2?
for you,if i want to create extrafields in category tab, is possible?
If you know there is a plugin that can do this?

**Comment by kavadas** [comment]
I am not aware of such a plugin. In order to get help regarding K2 you are requested to use our community forum at http://www.joomlaworks.net/forum/ .

**Comment by htongaria** [comment]
Great! It solved my problem! Saved my time too.

Hemant Tongaria
