### ISSUE TITLE
Is this normal with k2

### ISSUE THREAD

**Issue by LunaBawa** [joomlaworks/k2#233]
Please is this normal with k2 after installation it looks ok but during setup i see all this braces of codes showing up

![data source in k2_setup](https://cloud.githubusercontent.com/assets/11213175/6542966/cba117da-c509-11e4-96e4-03871fce8d7d.jpg)
![k2_config_screen](https://cloud.githubusercontent.com/assets/11213175/6542982/3b9590a2-c50a-11e4-880d-c1916a8a3bae.png)

**Comment by kavadas** [comment]
Hi,

I don't see how K2 is involved with this. You are editing a module ( not a K2 module ) in the module manager. K2 is not related with this.
