### ISSUE TITLE
Error: "Titel des Artikels fehlt" - after Update Joomla to 3.4 and K2 to 2.6.9

### ISSUE THREAD

**Issue by Robdebert** [joomlaworks/k2#234]
I had a joomla 3.3.6, that i updated to 3.4 and after that updated from K2 2.6.8 to 2.6.9.
I cleared every cache i could find.

When i wanted to open an article in the frontend it says "404 - article not found". Menu-settings seem to be correct. At least i changed nothing.

Trying to edit the k2-article in the backend (where the item exists and the access-rights are set correctly) directly on page load a javascript alert message appears saying: "Titel des Artikels fehlt". Don't know the english original, but i would guess: "title of article missing" or "missing item-title".

What could this be?

![k2 missing item title](https://cloud.githubusercontent.com/assets/1737455/6635514/58ecbe9e-c967-11e4-9ebf-374a3a31a8c0.PNG)

**Comment by kavadas** [comment]
Duplicate with this : https://github.com/joomlaworks/k2/issues/232 .
