### ISSUE TITLE
[module rss feed] sef generated rss feed gives an error

### ISSUE THREAD

**Issue by raramuridesign** [joomlaworks/k2#235]
HI Guys
joomla 3.4.0
k2, latest dev build
using joomla SEF

When creating a module to generate a RSS feed from different categories, we are getting an error when SEF is on.
When SEF is off the rss link works with no issue.

Link looks like this: http://mydomain.com/xxx/itemlist.feed?moduleID=276
error generated
-------------------------------------
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 SQL=SELECT a.id FROM gd_k2_categories as a WHERE a.published = 1 AND a.access IN(1,1) AND a.trash = 0 AND a.parent=
-------------------------------------

This only happens when SEF is on.
Turn SEF off and it works.

Could you please let us know if this is an issue with the module or something else.
Thanks
Matthew

**Comment by kavadas** [comment]
Hi,

Just tested and everything works fine for me. How did you generate that link? Is it the link provided by the K2 content module?

Also keep in mind that this query is not included in K2, so it might be a third-party extension causing this.

**Comment by raramuridesign** [comment]
Thanks, I will see if a 3rd party is causing this and revert and let you know.
