### ISSUE TITLE
Error saving items in K2

### ISSUE THREAD

**Issue by Vickula** [joomlaworks/k2#237]
Having problems saving items in K2 - have upgraded to Joomla v3.4.1 from 3.2.2, K2 v2.6.9 from v2.6.7 and php 5.4.30 from php 5.3.28 after the problem developed but it is still happening. 

On save I get a blank white screen. New items are saved but cannot attach images either by uploading or via items already on the server. 

Any help would be appreciated Thanks

**Comment by kavadas** [comment]
Hi,

This is a place to submit verified issues, not getting help. In order to get help you are kindly requested to use our community forum at http://www.joomlaworks.net/forum/ .
