### ISSUE TITLE
Rating block is invalid HTML

### ISSUE THREAD

**Issue by jozsefke** [joomlaworks/k2#243]
I have tried to validate my site using the W3 validator, but to my surprise it has given a lot of errors related to K2. The anchor tags inside the rating block have invalid 'rel' values, according to the validator.

You can see it here: http://validator.w3.org/check?uri=http://demo.getk2.org/item.

I know it doesn't affect SEO or functionality, but I think it's important to have a valid website. Could you please consider it in the next release to make the component HTML5 valid?

**Comment by kavadas** [comment]
The markup has changed already: https://github.com/joomlaworks/k2/blob/master/components/com_k2/templates/default/item.php#L183-L188  .
