### ISSUE TITLE
Simpler search page URL

### ISSUE THREAD

**Issue by jozsefke** [joomlaworks/k2#244]
When you initiate a search with the K2 Tools module with search function, the URL looks like this: 'mydomain/search?searchword=test&categories='. Is it possible to change it so when the search is for all the categories, the categories part wouldn't display? The URL would be much simpler that way like only 'mydomain/search?searchword=test'.

**Comment by kavadas** [comment]
Hi,

You can easily do this on an override:
```php
<?php if($categoryFilter): ?>
<input type="hidden" name="categories" value="<?php echo $categoryFilter; ?>" />
<?php endif; ?>
```
