### ISSUE TITLE
Option for turning off squeezebox in K2 parameters

### ISSUE THREAD

**Issue by kbrookes** [joomlaworks/k2#246]
Many of us with Bootstrap-based templates experience an issue whereby the .modal class for itemImages in item.php and other views causes the element to disappear, due to to Bootstrap.css settings .modal to display:none;.

While it's completely understandable that the .modal class cannot be removed for backwards compatibility, when we try to use template overrides to implement Bootstrap modal functionality into K2 templates there are some Mootools conflicts that come to the fore, namely with the Squeezebox that is instansiated in the head of the document.

This can be resolved by disabling Mootools and using Regex or ReReplacer to remove the Squeezebox code but it's a bit hit and miss.

An elegant solution that would maintain backwards compatibility for standard users while allowing those who heavily override their sites would be to include an option in the K2 parameters for turning off Squeezebox, alongside the jQuery and k2.css toggles.

This would solve a number of problems that those of us who Bootstrapify K2 face on every site we develop.

**Comment by d0ublezer0** [comment]
plugins\system\k2\k2.php
comment this:
    // Joomla! modal trigger
    /*
    if ( !$user->guest || (JRequest::getCmd('option') == 'com_k2' && JRequest::getCmd('view') == 'item') || defined('K2_JOOMLA_MODAL_REQUIRED') ){
    JHTML::_('behavior.modal');
    }
    */

**Comment by fevangelou** [comment]
We plan on scrapping the Joomla modal for the image in K2 v2.7.0 altogether and replace with a lighter and responsive alternative (e.g. SimpleBox http://fotis.co/projects/simplebox/ - an updated release to be exact).

Closing the issue. Expect the update to resolve this.
