### ISSUE TITLE
When getting item by json, the item hits count won't increase

### ISSUE THREAD

**Issue by newjie** [joomlaworks/k2#248]
These two lines are found in `com_k2\views\item\view.html.php` line 134

    // Increase hits counter
    $model->hit($item->id);

which I believe increases the item hits count when the item is displayed in a normal way. But in ·com_k2\views\item\view.json.php·, there are no such lines.

**Comment by kavadas** [comment]
Hi,

This is the intended behavior. We do not want to increase the pages view counter when the item is accessed through the JSON API.

**Comment by fevangelou** [comment]
@kavadas Let's add it in please. The change is minimal and it's valid. If we wanna build a web or mobile app on top of K2, we must keep some consistencies with how K2 already works for Joomla.
