### ISSUE TITLE
Only show READMORE button if full text exists

### ISSUE THREAD

**Issue by kairoen** [joomlaworks/k2#25]
A suggestion to hide "READ MORE" link if only introtext field in the DB contains characters. 

Suggestion to code:
if ( ($this->item->params->get('catItemReadMore')) && (strlen($this->item->fulltext)>0) ): ?>

line 272
file com_k2/templates/default/category_item.php

**Comment by fevangelou** [comment]
Lefteris is correct. It's easier to implement in a template override.

In pseudo coding: if fulltext is empty, hide readmore link

This is Joomla folks, not WP. Things like that are a piece of cake :)
