### ISSUE TITLE
K2 titles after upgrading to 3.4.4

### ISSUE THREAD

**Issue by fabricioventura** [joomlaworks/k2#250]
K2 titles after upgrading to 3.4.4

After upgrading to version 3.4.4 happens the following error in the administration of items and categories of k2.

To access or save an item or category:

Alert Error: Item must have a title!

**Comment by kricore** [comment]
Hello there,

Can you disable the "System - JCE" plugin (if JCE is installed) and try again?

**Comment by fabricioventura** [comment]
Wow !!

It was just that, thank you very much for your help!

**Comment by kricore** [comment]
You 're welcome :)
