### ISSUE TITLE
Uploading image not working

### ISSUE THREAD

**Issue by Twincarb** [joomlaworks/k2#252]
Since one of the recent updates, when a user attempted to upload an image using the Image tab, and select image to upload, the user can select an image and tell it to upload. However this image isn't uploaded. 

As a workaround I suggested using the media manager but we found this to have been broken by a recent update. I have been able to rectify that issue by reverting the code back to the original.

I can see the logic in the new code to only allow certain file types to be uploaded but us as system admins should decide what we want to allow to be uploaded using options.

https://github.com/joomlaworks/k2/commit/db131ad4faf5690fa8302c4e8a5d67f0bdca8b7c

The portion of code that I had to remove and replace with old is as below
+		$options = array('debug' => false, 'roots' => array( array('driver' => 'LocalFileSystem', 'path' => $path, 'URL' => $url, 'accessControl' => 'access', 'defaults' => $permissions, 'uploadAllow' => array('image', 'video', 'audio', 'text/plain', 'text/html', 'application/json', 'application/pdf', 'application/zip', 'application/x-7z-compressed', 'application/x-bzip', 'application/x-bzip2', 'text/css', 'application/msword', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.openxmlformats-officedocument.presentationml.presentation'), 'uploadOrder' => array('allow', 'deny'))));

**Comment by kavadas** [comment]
I have already answered to your comment in the commit regarding the media manager. Can you provide details regarding the image upload issue when using the image tab? Just tested with the development version and everything works fine.

**Comment by Twincarb** [comment]
rebuilt the site and issue cleared, believe it was a problem with the site in question.
