### ISSUE TITLE
Fatal error: Maximum execution time of 500 seconds exceeded i

### ISSUE THREAD

**Issue by srinath461** [joomlaworks/k2#253]
Fatal error: Maximum execution time of 500 seconds exceeded in C:\xampp\htdocs\medi\administrator\components\com_k2\lib\class.upload.php on line 5023

Joomla 3.4
K2 2.6.9
Template JSN BOOT
This happens when I am uploading a item with an image.

![k2-joomla-3](https://cloud.githubusercontent.com/assets/5940674/10716461/f1cad1fa-7b5f-11e5-820e-068238d61796.PNG)
Any suggestions how to solve this.

**Comment by kavadas** [comment]
Hi,

It seems that the 500 seconds are not enough for your server to upload the image and process it. Try to use a smaller image.
