### ISSUE TITLE
K2 Images

### ISSUE THREAD

**Issue by eoininho** [joomlaworks/k2#254]
Hi All

I am using K2 in a Gavick template I purchased and I am having issues with preview images that appear on the homepage once the post is created. 

I want to be able to use embedded images, and have these appear as the preview image. 

Currently it seems you need to upload a photo to be able to assign it as the 'preview' image on the homepage for articles you have added. i want to be able to use embedded images, without the need to save them on my pc and upload them. 

Please can you assist. 

thanks
Eoin

**Comment by kavadas** [comment]
Hi,

This is a place for submitting issues, not getting help. In order to get help regarding K2 you are kindly requested to use our forum at http://www.joomlaworks.net/forum .
