### ISSUE TITLE
"Enable Gravatar.com avatar lookup for non-registered commenters" actually affects every avatar lookup

### ISSUE THREAD

**Issue by giruf** [joomlaworks/k2#256]
Hi,
I freshly installed K2 2.6.9 and published a test article and I noticed that the Super User avatar (which is not set) was displayed as an image not found.
Looking at the source of the page I saw that the component is trying to access the image:

//www.gravatar.com/avatar/e713eb89b6ad953778b46784d0d371a0?s=100&default=http%3A%2F%2Fwww.mysite.com%2Fcomponents%2Fcom_k2%2Fimages%2Fplaceholder%2Fuser.png

which does not exist.
So looking at the code i ended up in the file:

/web/components/com_k2/helpers/utilities.php

in the function getAvatar() at line 69:
    if ($params->get('gravatar') && !is_null($email))

the parameter 'gravatar' refers to the option in the Subject and in fact setting this to 'No' solves my problem (now it shows the correct image: /components/com_k2/images/placeholder/user.png)

I think this is unintended behaviour.

Thank You very much for reading

**Comment by kavadas** [comment]
Hi,

Is your site available online? K2 tells Gravatar to serve you the exact same image ( /components/com_k2/images/placeholder/user.png ) for emails that do not match a Gravatar account. The only reason it will not do that is if your site is not available online.

**Comment by giruf** [comment]
Hi kavadas,

Thank You for the answer, no my site is not currently available online so everything normal.

Sorry for wasting Your time!

**Comment by kavadas** [comment]
No, problem. You are welcome.
