### ISSUE TITLE
Undefined constant JPATH_COMPONENT_ADMINISTRATOR K2 v2.6.8

### ISSUE THREAD

**Issue by vancanneyt** [joomlaworks/k2#257]
Following errors occur in Joomla 3.4.4: 
Got error 'PHP message: PHP Notice:  Use of undefined constant JPATH_COMPONENT_ADMINISTRATOR - assumed 'JPATH_COMPONENT_ADMINISTRATOR' in /components/com_k2/models/itemlist.php on line 15
PHP message: PHP Notice:  Use of undefined constant JPATH_COMPONENT_ADMINISTRATOR - assumed 'JPATH_COMPONENT_ADMINISTRATOR' in /components/com_k2/models/item.php on line 15

**Comment by kavadas** [comment]
I cannot verify the issue. I don't get this under Joomla! 3.4.5 . Joomla! 3.4.4 contains a serious security issue. You are suggested to update to 3.4.5 as soon as possible. If you do and the issue persists just let me know.

**Comment by vancanneyt** [comment]
Same under J!3.4.5 and PHP5.6.13

**Comment by vancanneyt** [comment]
Similar report on joomlaworks forum:
http://www.joomlaworks.net/forum/k2-en/37002-wondering-if-k2-might-prevent-admin-login

It there states that it is due to a third party K2 plugin. In my case this isn't the issue, K2 runs without any other plugin and/or modification.  I do know it is just a php notice but it shouldn't have to be that way. 
Plus if you google for the error message in combination with com_k2 you'll find multiple sites that have the issue. 
Disabling error reporting is one thing, but making code notices and error free is also important.

**Comment by kavadas** [comment]
It is a third party extension on your issue too. Probably a third party extension is trying to use the specific K2 file outside K2 context. That's why you get this.

This constant is defined by Joomla! when K2 is rendered.
