### ISSUE TITLE
K2 "ITEM MUST HAVE A TITLE"

### ISSUE THREAD

**Issue by paul-100** [joomlaworks/k2#258]
I got the error above on my production site when adding google analytics to my gantry framework website [Joomla 3.4.1, k2 2.6.7]. If you have disabled JCE system plugin, Multilingual plugin and still getting the same issue please disable your google analytics.

Pass this message along to everyone it is a serious nightmare

**Comment by kavadas** [comment]
Hi,

This issue has already been fixed. Details can be found at https://github.com/joomlaworks/k2/issues/232 .
