### ISSUE TITLE
K2 Media Manager Issue on Joomla 3.4.x - not showing anything

### ISSUE THREAD

**Issue by Robdebert** [joomlaworks/k2#259]
I also discovered an issue with the media manager, that does not show anything.
I found out, how to fix this (in the core files):

file: **administrator/components/com_k2/helpers/html.php**
starting a about line 70:

if($mediaManager)
{
	// Media Manager not showing, when this script is activated. Therefore we comment it out in the backend. 
	// $document->addScript('//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js');
}
else
{
	JHtml::_('behavior.framework');
	if ($application->isAdmin() || ($application->isSite() && $params->get('jQueryHandling')))
	{
		JHtml::_('jquery.framework');
	}
}

**Comment by Robdebert** [comment]
![image](https://cloud.githubusercontent.com/assets/1737455/11992520/5a3ba17e-aa27-11e5-82b0-eb0f37e405db.png)

Here's a screenshot.

**Comment by kavadas** [comment]
Hi,

Can you test with the development version from http://getk2.org/assets/get/ ?

**Comment by kavadas** [comment]
I cannot reproduce the issue. No errors for me both in 2.6.9 and 2.7.0 DEV version. I don't think that the error is caused by K2 files. Feel free to reopen the issue if you have more information regarding this.

**Comment by simbus82** [comment]
I have the same identical error in K2 2.7.1 in one site. I have no particular extension. Joomla is 3.6.2.
PHP 5.6 is the same that work well in other sites with k2

**Comment by Mharbs** [comment]
I also have same problem. Media manager of K2 is not showing. Here's the error.. Can someone help me please...
![k2Mediamanager](https://user-images.githubusercontent.com/75844515/101910141-80478b80-3bf9-11eb-98de-505690294b4f.png)

**Comment by fevangelou** [comment]
Delete /media/k2/assets/vendors/ and re-install K2.
