### ISSUE TITLE
Offer the ability to deactivate OG meta tags

### ISSUE THREAD

**Issue by heyjoecampbell** [joomlaworks/k2#260]
Offer a parameter to turn on/off OG meta tags.

**Comment by fevangelou** [comment]
Not a fan of Facebook? :D

**Comment by fevangelou** [comment]
Before I add a dozen checks for that little switch, what is the rationale behind your request?

**Comment by heyjoecampbell** [comment]
Someone is likely to use another extension to produce OG tags, since K2 does not provide control over the tag and only offers limited tag types (missing: video, geo, etc.)

Not offering a parameter to deactivate it can lead to duplicate OG tags. 

Then you have the principle of the matter. It is not good practice to output code that an administrator can not control (without hacking)

Personally, I have committed out the OG tags (http://www.joomlaworks.net/forum/k2-en/41210-k2-power-tip-remove-open-graph-meta-k2-hack) and use extra fields to control most of my meta tags (among other things)

I simply submitted this request to reduce the need for the hack and to help others less savvy :)

**Comment by KannanNaidu** [comment]
Use the upcoming new version 3 :) 
FB metatags can be enabled and disabled in social settings.

**Comment by fevangelou** [comment]
We'll add the option.

**Comment by heyjoecampbell** [comment]
Thanks :)
