### ISSUE TITLE
Cache issue?

### ISSUE THREAD

**Issue by iandalkin** [joomlaworks/k2#261]
PHP 5.5.30 ~ Apache 2.2.31 ~ Joomla 3.4.8 ~ K2 2.6.9
Moderate or progressive caching 'On' breaks site navigation: see cloned site at http://siterescue.com.au/bigfixtester. In this installation, both SEF URLs and URL rewriting are disabled but enabling them also not working.

Actual site is at www.thebigfix.org with SEF URLs, URL rewriting and Cache all disabled. All working.

**Comment by iandalkin** [comment]
Many thanks to George Papadakis for insight into this issue. I have referred it to the developer.

**Comment by kricore** [comment]
Hello,

K2 will not affect your navigation. This is a Joomla! issue. The modules probably, shouldn't be cached.

**Comment by iandalkin** [comment]
Hello Krikor,

This solution by Georgios  Papadakis ‘nearly’  works but there are still cache issues.  Is there anything contained in this reply by Georgios that might lead you to re-examine the issue? It has been reported elsewhere:

George replied:

Not all controllers are setting the $urlparams

e.g.
components/com_k2/controllers/itemlist.php
is indeed setting $urlparams

...
if (K2_JVERSION != '15')
{
    $urlparams['limit'] = 'UINT';
    $urlparams['limitstart'] = 'UINT';
    $urlparams['id'] = 'INT';
    $urlparams['tag'] = 'STRING';
    $urlparams['searchword'] = 'STRING';
    $urlparams['day'] = 'INT';
    $urlparams['year'] = 'INT';
    $urlparams['month'] = 'INT';
    $urlparams['print'] = 'INT';
    $urlparams['lang'] = 'CMD';
    $urlparams['Itemid'] = 'INT';
}
parent::display($cache, $urlparams);
but

neither components/com_k2/controllers/latest.php
nor its parent controller: components/com_k2/controllers/controller.php are setting $urlparams, .../latest.php only has:
...
parent::display($cache);
you can copy the IF statement into the .../latest.php file,

and replace parent::display($cache); with  parent::display($cache, $urlparams);
and it should work (clear cache once after the change)

it is not a Joomla bug



________________________
Ian Dalkin
http://www.siterescue.com.au
101 Wentworth Street
Blackheath 2785
NSW Australia
Ph:  +61 2-47877533 0434-575470

**Comment by iandalkin** [comment]
This plugin may fix the issue. As usually advised, test on a test site: https://dj-extensions.com/downloads/cat_view/194-k2-fix-plugin

**Comment by iandalkin** [comment]
Hello again Krikor,

Ref: www.thebigfix.org

Despite spending more than a month trying to fix this issue, I still can’t get it to work (ie. when ‘cache’ is turned ‘on’, the site breaks.  The issue is now beyond urgent and I will do whatever I have to do to get a fix.  Can you please help?  If it turns out to be a simple misconfiguration on my part, I will gladly pay you for your time (I will pre-pay if necessary).  The Super Admin login to the site is via u/p rsjoomlatester

Any or all help would be much appreciated.  I have an Akeeba backup of the site so son’t be concerned if the site doesn’t work.  I restore it to proper functioning by simply turning off cache, clearing cache and remove cached files from the browser.

Regards,
________________________
Ian Dalkin
http://www.siterescue.com.au
101 Wentworth Street
Blackheath 2785
NSW Australia
Ph:  +61 2-47877533 0434-575470


The latest from Georgics Papadakis;

EVERY controller needs to set proper $urlparams

latest.php controller of k2 is not setting any, neither is its parent controller, thus it is using the platform defaults which do not include "Itemid" !
i hacked Joomla code and made a function stack printout and also printed the passed $urlparams, they are empty, as expected by looking at the code, thus the platform defaults which do not include "Itemid" were used !  
Let's not guess, and confirm that every INDIVIDUAL CONTROLLER is setting these properly,

if some view of Joomla is broken in a similar way it should be fixed too BUT this is not related

my component caching was broken in a similar way 2 years ago - i found no Joomla caching bug !! other than the requirement that every component needing to set the safeurlparams properly, which is not a bug

**Comment by kavadas** [comment]
@iandalkin 

The latest view accepts no URL params, that's why the controller does not include that code.

K2 should work fine with caching enabled. I guess the issue is caused by a third-party extension or your server setup.

If you think that the issue is caused by K2, provide detailed instructions ( which link fails etc. ) so we can reproduce that.

**Comment by iandalkin** [comment]
Thanks for that.  Please let me know how to pass Super Admin access so you can see this in action .. site works fine, cache enabled and it falls over.  Any help appreciated.  If it’s a server fail, what are the parameters (SQL or PHP version etc.) that would dictate this?  Sorry to harass you but I simply can’t get it to work.

Cheers,

________________________
Ian Dalkin
http://www.siterescue.com.au
101 Wentworth Street
Blackheath 2785
NSW Australia
Ph:  +61 2-47877533 0434-575470

**Comment by kavadas** [comment]
You are asking for help, you are not reporting an issue. Let's continue the discussion to the forum at rthe topic you have already opened.
