### ISSUE TITLE
Missing K2 item og:image meta tag, if Joomla! is installed in subdirectory

### ISSUE THREAD

**Issue by sevenstudio** [joomlaworks/k2#262]
Hello,

this is a small, but important issue, if Joomla is used in a subdirectory (domain.com/directory/), K2 item og:image tag is not generated due to an error in the path to the file.

In the view file <pre>components/com_k2/views/item/view.html.php</pre>

in lines 560 - 569 we have:
<pre>
		if ($item->$facebookImage)
		{
			$parts = parse_url($item->$facebookImage);
			if (JFile::exists(JPATH_SITE.$parts['path']))
			{
				$image = substr(JURI::root(), 0, -1).str_replace(JURI::root(true), '', $item->$facebookImage);
				$document->setMetaData('og:image', $image);
				$document->setMetaData('image', $image);
			}
		}
</pre>

but here both <code>JPATH_SITE</code> and <code>$parts['path']</code> includes subdirectory name in the path, so in a result <code>JFILE::exist</code> checks whether a file exists in the wrong directory <code>..../subdirectory/subdirectory/media/k2/items/cache/....</code> .

Proposed simple fix, replacing lines 560 - 569 with:
<pre>
		if ($item->$facebookImage)
		{
			if (JFile::exists(JPATH_SITE . str_replace(JURI::root(true), '', $item->$facebookImage)))
			{
				$image = substr(JURI::root(), 0, -1) . str_replace(JURI::root(true), '', $item->$facebookImage);
				$document->setMetaData('og:image', $image);
				$document->setMetaData('image', $image);
			}
		}
</pre>

This should work regardless of the place that Joomla is installed.
It would be great if anyone could look at this issue in a spare time ;)

Btw. if there are any plans, to release 2.7.0 anytime soon? Interface looks great!

Greetings!

**Comment by HarikalarKutusu** [comment]
Kudos to sevenstudio :) This was my nightmare...

**Comment by sevenstudio** [comment]
@HarikalarKutusu kudos to @kavadas for providing fix ;)

btw. @ kavadas. Is there is any reason to keep meta image tag here? og:image does the job.

Also thanks for providing fix here!
