### ISSUE TITLE
Problem saving new K2 Content Module

### ISSUE THREAD

**Issue by gaelicwinter** [joomlaworks/k2#265]
When I try to save a new K2 Content Module, the save is not completed and no errors are shown. It fails in the javascript field verification process with a blank id. Here is a screenshot:

imgur.com/8HRu06E

I rolled back this file to the previous version:

administrator/components/com_k2/elements/item.php

and now the module saves, as shown in this screenshot:

imgur.com/pcM1hwr

The problem seems to be in this line of code, line 56:

New version:

            $html = '<span class="input-append">
            <input type="text" id="'.$name.'_name" value="'.htmlspecialchars($item->title, ENT_QUOTES, 'UTF-8').'" disabled="disabled" />
            <a class="modal btn" title="'.JText::_('K2_SELECT_AN_ITEM').'"  href="'.$link.'" rel="{handler: \'iframe\', size: {x: 700, y: 450}}"><i class="icon-file"></i>'.JText::_('K2_SELECT').'</a>
            <input type="hidden" class="required modal-value" id="'.$name.'_id" name="'.$fieldName.'" value="'.$value.'" />
            </span>';

Old version:

            $html = '<span class="input-append">
            <input type="text" id="'.$name.'_name" value="'.htmlspecialchars($item->title, ENT_QUOTES, 'UTF-8').'" disabled="disabled" />
            <a class="modal btn" title="'.JText::_('K2_SELECT_AN_ITEM').'"  href="'.$link.'" rel="{handler: \'iframe\', size: {x: 700, y: 450}}"><i class="icon-file"></i>'.JText::_('K2_SELECT').'</a>
            <input type="hidden" class="required modal-value" id="'.$name.'_id" name="'.$fieldName.'" value="'.( int )$value.'" />
            </span>';

You can see the ( int ) is missing at the end of the line right before the $value variable.

I don't understand the original issue for making the change so I can't comment on the proper way to resolve it, but I know it does solve my problem.

Thanks for your help,
Paul

**Comment by kavadas** [comment]
Hi,

This is related with https://github.com/joomlaworks/k2/issues/153 . 

We tried to fix that issue but it seems it opened a new one.
