### ISSUE TITLE
Change the language in which the K2 item is published

### ISSUE THREAD

**Issue by GiannisZ** [joomlaworks/k2#266]
Hello,

Is it possible to change the default "All" language in which the K2 Item is published? 

For example, I have two languages (Greek and English) and I would like to change the option of the following image and make "Greek" as the default language.

Thanks :)

<img width="371" alt="2016-01-27 4 43 21" src="https://cloud.githubusercontent.com/assets/7051009/12616912/02722bd4-c516-11e5-984f-f9743407740b.png">

**Comment by kavadas** [comment]
Hi,

This is a place for submitting issues, not getting help. In order to get help for K2 you are kindly requested to use the K2 community forum at http://www.joomlaworks.net/forum/k2-en .
