### ISSUE TITLE
[K2 2.7.0] The new styled radio button does not turn green with all K2 modules when selected

### ISSUE THREAD

**Issue by KannanNaidu** [joomlaworks/k2#267]
The radio button select option in k2 module configuration does not change to green when selected on all K2 default modules.

Using the isis administrator template. 

![administration - modules_ k2 content](https://cloud.githubusercontent.com/assets/1253496/12792891/d706e632-cae8-11e5-853d-e8c891acbea2.png)

**Comment by kricore** [comment]
Thank you for reporting this Kannan. I will commit a solution.

**Comment by KannanNaidu** [comment]
This also happens in the extra fields page. The published option value
![fireshot screen capture 040](https://cloud.githubusercontent.com/assets/1253496/12870140/e0455efa-cd71-11e5-9c64-0d89a45b8aa1.png)

**Comment by KannanNaidu** [comment]
@kricore if i revert back before this commit - [https://github.com/joomlaworks/k2/commit/c00c2869c9e63410da15d40b65edfec7ee05622e#diff-99ff5589323f0f9433ec1889b1aef979](url) it seems to work fine (UI improvements for medium sizes resolutions in k2.module.css) 

Old code : 
`.form-horizontal .controls label, .controls label { min-width:85px;width:auto; text-align:center; border:1px solid #d4d6d8;line-height:33px;vertical-align:top;height:33px;font-size:12px;margin:0 -2px;padding:0 13px;
color:#8a8c8c;display:inline-block;vertical-align:middle;white-space:nowrap;background-color:#eff1f1;
box-shadow:0 1px 1px rgba(65,64,66,.14), inset 0 1px 0 #fff; }`

**Comment by kricore** [comment]
I pushed a solution. It is not super clean but we have to control several aspects over several different views which we have no control over.
