### ISSUE TITLE
[item] Ordering of Attachments & Renaming of attachment title

### ISSUE THREAD

**Issue by raramuridesign** [joomlaworks/k2#36]
When uploading attachments to Items the possibility to order the items does not exist.

It would be a great feature to be able to:

1. order the attachments with an ajax type interface
2. ability to rename the title of the attachments using inline editing

**Comment by leeburstroghm** [comment]
What . There is no ordering for attachments.. You have got to be kidding?!!

**Comment by fevangelou** [comment]
We'll do our best to have this in K2 2.7.1.
