### ISSUE TITLE
josetta and extrafields

### ISSUE THREAD

**Issue by effidoc** [joomlaworks/k2#40]
I just installed josetta on joomla 3.1.5 and k2 2.6.7 and tried to translate a k2 item ! it was first impossible to save. 
i went on josetta forum and found out there was a k2 dev version that repaired it  
so I tried it and the saving was possible. 

though there is a new problem with extrafield : it seems empty in the original language and is impossible to copy because it ask to set a category that is not available.

![josetta-k2](https://f.cloud.github.com/assets/5610183/1274797/6836c3f8-2dce-11e3-9eb0-ae236e3ed67d.jpg)
so the translation has been created WITHOUT the extrafields that is not useful !

**Comment by kavadas** [comment]
Josetta integration plugins wii be removed from the next version .

https://github.com/joomlaworks/k2/commit/4c7189a558c9beb128e5eebf4dc44bf44c5dbbeb
